#!/bin/bash
### SBATCH --partition=debug
###SBATCH --partition=general
### SBATCH --partition=lo-core # This can be as long as 7 days
#SBATCH --partition=priority
#SBATCH --account=chl23026
#SBATCH --qos=me_epyc        # chl23026, me_epyc   
#SBATCH --constraint=epyc128 # This is optional
#SBATCH --nodes=1
#SBATCH --ntasks=126
#SBATCH --time=30-00:00:00
#SBATCH --mail-user=duc.nguyen@uconn.edu      # Destination email address
#SBATCH --mail-type=ALL                       # Event(s) that triggers email notification
#SBATCH --job-name=LSA_SDDC_Pr10
#SBATCH --output=matlab_output_%j
export SLURM_EXPORT_ENV=ALL
#export I_MPI_FABRICS=shm,tcp

##the slurm number to restart simulation... This need full state to be stored.
SUBMITDIR=$SLURM_SUBMIT_DIR
WORKDIR=/scratch/chl23026/jms24002/matlab_$SLURM_JOB_ID
mkdir -p "$WORKDIR" && cp -r *.m "$WORKDIR" && cp submit_matlab_uconn "$WORKDIR" && cd "$WORKDIR" || exit -1

# ssh -y jms24002@hpc2.storrs.hpc.uconn.edu
# LSA_SDDC_Pr10000: jobid 21646617 : running
# LSA_SDDC_Pr1000: jobid 21646619 : pending
# LSA_SDDC_Pr100: jobid 21642114 : running 
# LSA_SDDC_Pr10: jobid 21655714 : running <<--
# LSA_reducedSDDC_Pr10: jobid 21655719 : running <<--
# Required modules
module load matlab

# Run MATLAB executable
matlab -nodisplay -nosplash -nodesktop -r maxGrowthRateMap_RiPe_Lambda2_tau0_01\; exit\;


cd "$SUBMITDIR" && cp matlab_output_$SLURM_JOB_ID "$WORKDIR"

